### ISSUE TITLE
Adicionei o pacote mas as mensagens ainda estão em inglês

### ISSUE THREAD

**Issue by rodrigoassis1996** [Leomhl/laravel-5.4-pt-br-localization-polite#1]
Eu adicionei o pacote ao diretório lang do laravel e alterei o 'locale' na linha 80 do arquivo app.php mas as mensagens usadas no projeto ainda permanecem em inglês. Apenas quando eu substituo os arquivos da pasta 'en' pelos arquivos do pacote, é que a tradução funciona. O que pode ser?

**Comment by Leomhl** [comment]
Olá @rodrigoassis1996, pode ser cache. Se estiver rodando localmente no servidor artisan, interrompe e rode rode novamente. Caso seja cloud, reinicie seu servidor (apache/nginx). Caso não resolva o problema, entre em contato novamente para vermos as outras alternativas.

**Comment by rodrigoassis1996** [comment]
@Leomhl , estou rodando localmente no servidor artisan. Interrompi a execução (ctrl + c no prompt) e rodei novamente mas nenhum resultado. Continua usando a tradução em inglês.

**Comment by rodrigoassis1996** [comment]
@Leomhl consegui aqui! Decidi limpar tudo: cache, config, rotas, views, o cache do composer... E aí atualizei o composer e funcionou. Vlw pela ajuda!

**Comment by Leomhl** [comment]
Que ótimo que conseguiu resolver @rodrigoassis1996 ! Geralmente o laravel cria cache das configurações e provavelmente o artisan serve estava utilizando o config "cacheado"  com a versão en. Bom uso da biblioteca ;)
